// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\colleage\paperwork\iotj2020\opendds\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "MessengerC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "MessengerC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// c:\colleage\paperwork\iotj2020\opendds\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Messenger::Message &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.subject_id) &&
    (strm << _tao_aggregate.utc) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.posstatus)) &&
    (strm << _tao_aggregate.lat) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.lat_dir)) &&
    (strm << _tao_aggregate.lon) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.lon_dir)) &&
    (strm << _tao_aggregate.speed) &&
    (strm << _tao_aggregate.track) &&
    (strm << _tao_aggregate.date) &&
    (strm << _tao_aggregate.mag) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.mag_dir)) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.mode)) &&
    (strm << _tao_aggregate.check);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Messenger::Message &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.subject_id) &&
    (strm >> _tao_aggregate.utc) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.posstatus)) &&
    (strm >> _tao_aggregate.lat) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.lat_dir)) &&
    (strm >> _tao_aggregate.lon) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.lon_dir)) &&
    (strm >> _tao_aggregate.speed) &&
    (strm >> _tao_aggregate.track) &&
    (strm >> _tao_aggregate.date) &&
    (strm >> _tao_aggregate.mag) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.mag_dir)) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.mode)) &&
    (strm >> _tao_aggregate.check);
}

TAO_END_VERSIONED_NAMESPACE_DECL



